name: Python Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt # Install test dependencies
      
    - name: Run Tests
      run: |
        pytest tests/ --cov=src --cov-report=xml --cov-report=html
    
    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: htmlcov/
